# Generated by Django 4.2.3 on 2023-07-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=128, unique=True)),
                ('login', models.CharField(max_length=128, unique=True)),
                ('passwordHash', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserToRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField()),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.role')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('subgroup', models.CharField(max_length=128)),
                ('price', models.BigIntegerField()),
                ('deleted', models.BooleanField()),
                ('description', models.CharField(max_length=1024)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='idUserCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
    ]
